import { Medico } from "@/types/medico";

export const fakeData: Medico[] = [
    {
        id: "1",
        nome: "João Guilherme da Silva",
        conselho_medico: "CRM",
        uf_conselho: "RN",
        num_conselho: "123456",
        cbo: "123456",
        cpf: "12345678900",
        lagradouro: "Rua da Paz",
        bairro: "Paz",
        cidade: "Paz",
        uf: "Paz",
        cep: "123456",
        telefone: "123456",
        email: "",
        clinica: "Hospital da Paz"
    },
    {
        id: "2",
        nome: "Maria Fernanda Oliveira",
        conselho_medico: "CRM",
        uf_conselho: "SP",
        num_conselho: "654321",
        cbo: "654321",
        cpf: "12345678900",
        lagradouro: "Avenida da Saúde",
        bairro: "Saúde",
        cidade: "Saúde",
        uf: "SP",
        cep: "654321",
        telefone: "654321",
        email: "",
        clinica: "Hospital da Saúde"
    },
    {
        id: "3",
        nome: "Pedro Henrique Santos",
        conselho_medico: "CRM",
        uf_conselho: "RJ",
        num_conselho: "987654",
        cbo: "987654",
        cpf: "12345678900",
        lagradouro: "Rua dos Médicos",
        bairro: "Médicos",
        cidade: "Médicos",
        uf: "RJ",
        cep: "987654",
        telefone: "987654",
        email: "",
        clinica: "Hospital dos Médicos"
    },
    {
        id: "4",
        nome: "Ana Carolina Souza",
        conselho_medico: "CRM",
        uf_conselho: "MG",
        num_conselho: "456789",
        cbo: "456789",
        cpf: "12345678900",
        lagradouro: "Avenida da Esperança",
        bairro: "Esperança",
        cidade: "Esperança",
        uf: "MG",
        cep: "456789",
        telefone: "456789",
        email: "",
        clinica: "Hospital da Esperança"
    },
    {
        id: "5",
        nome: "Lucas Oliveira",
        conselho_medico: "CRM",
        uf_conselho: "RS",
        num_conselho: "135792",
        cbo: "135792",
        cpf: "12345678900",
        lagradouro: "Rua dos Sonhos",
        bairro: "Sonhos",
        cidade: "Sonhos",
        uf: "RS",
        cep: "135792",
        telefone: "135792",
        email: "",
        clinica: "Hospital dos Sonhos"
    },
    {
        id: "6",
        nome: "Juliana Santos",
        conselho_medico: "CRM",
        uf_conselho: "BA",
        num_conselho: "246813",
        cbo: "246813",
        cpf: "12345678900",
        lagradouro: "Avenida da Alegria",
        bairro: "Alegria",
        cidade: "Alegria",
        uf: "BA",
        cep: "246813",
        telefone: "246813",
        email: "",
        clinica: "Hospital da Alegria"
    },
    {
        id: "7",
        nome: "Rafaela Lima",
        conselho_medico: "CRM",
        uf_conselho: "PE",
        num_conselho: "579135",
        cbo: "579135",
        cpf: "12345678900",
        lagradouro: "Rua das Flores",
        bairro: "Flores",
        cidade: "Flores",
        uf: "PE",
        cep: "579135",
        telefone: "579135",
        email: "",
        clinica: "Hospital das Flores"
    },
    {
        id: "8",
        nome: "Gustavo Almeida",
        conselho_medico: "CRM",
        uf_conselho: "CE",
        num_conselho: "802467",
        cbo: "802467",
        cpf: "12345678900",
        lagradouro: "Avenida da Liberdade",
        bairro: "Liberdade",
        cidade: "Liberdade",
        uf: "CE",
        cep: "802467",
        telefone: "802467",
        email: "",
        clinica: "Hospital da Liberdade"
    },
    {
        id: "9",
        nome: "Carolina Oliveira",
        conselho_medico: "CRM",
        uf_conselho: "SC",
        num_conselho: "159357",
        cbo: "159357",
        cpf: "12345678900",
        lagradouro: "Rua dos Amigos",
        bairro: "Amigos",
        cidade: "Amigos",
        uf: "SC",
        cep: "159357",
        telefone: "159357",
        email: "",
        clinica: "Hospital dos Amigos"
    },
    {
        id: "10",
        nome: "Fernando Silva",
        conselho_medico: "CRM",
        uf_conselho: "ES",
        num_conselho: "468024",
        cbo: "468024",
        cpf: "12345678900",
        lagradouro: "Avenida da Felicidade",
        bairro: "Felicidade",
        cidade: "Felicidade",
        uf: "ES",
        cep: "468024",
        telefone: "468024",
        email: "",
        clinica: "Hospital da Felicidade"
    }
];
